export default [
  { src: '/gallery/1.jpg' },
  { src: '/gallery/2.jpg' },
  { src: '/gallery/3.jpg' },
  { src: '/gallery/4.jpg' },
  { src: '/gallery/5.jpg' },
  { src: '/gallery/6.jpg' },
  { src: '/gallery/7.jpg' },
  { src: '/gallery/8.jpg' },
  { src: '/gallery/9.jpg' },
  { src: '/gallery/10.jpg' },
  { src: '/gallery/11.jpg' },
  { src: '/gallery/12.jpg' },
  { src: '/gallery/13.jpg' },
  { src: '/gallery/14.jpg' },
  { src: '/gallery/15.jpg' },
  { src: '/gallery/16.jpg' },
  { src: '/gallery/17.jpg' },
];
